### ISSUE TITLE
哈夫曼编码压缩，对bmp格式会反而变得很大。。是原文件的好几倍

### ISSUE THREAD

**Issue by qwq2519** [yangyongkang2000/C-Programming#1]
RT

**Comment by yokeman-young** [comment]
是不是BMP格式图片很小？ 对于文件很小的话,压缩过程中额外写入标记造成的代价大于压缩本身的代价。

**Comment by qwq2519** [comment]
我压缩了一张33mb的bmp，压缩后是29mb，比较好。要是小点的图片等格式就会是十几倍的源文件大小。打扰了

**Comment by qwq2519** [comment]
请问读入文件的时候，采用缓冲区读入的优点是什么，一次性读入存入一个vector会更优吧

**Comment by yokeman-young** [comment]
> 请问读入文件的时候，采用缓冲区读入的优点是什么，一次性读入存入一个vector会更优吧

应该没啥优点，当时写的时候没考虑到。一次性读入vector效率更高，但即使从缓冲区读入，也不会浪费很大的时间代价，IO读取是占主流的。

**Comment by yokeman-young** [comment]
> 我压缩了一张33mb的bmp，压缩后是29mb，比较好。要是小点的图片等格式就会是十几倍的源文件大小。打扰了

- [ ] 可以使用一些压缩软件测试经常用的测试集，比如：
benchmark for 100MB of Large Text Compression Benchmark (enwik8, see http://www.mattmahoney.net/dc/textdata.html): (for latest enwik8 benchmark result, see github actions)
