### ISSUE TITLE
关于哈夫曼编码的压缩的一些问题

### ISSUE THREAD

**Issue by qwq2519** [yangyongkang2000/C-Programming#2]
```
bool b = std::get<T>(*std::max_element(table.begin(), table.end(), [](auto &i, auto &j) {
            return std::get<T>(i) < std::get<T>(j);
        })) <= (L<T, 2> + 1);//最长的编码长度是否小于某个阈值
```
这个阈值是怎么确定的
以及存数据的bitset的table和普通的整型数table

```
 constexpr int N = std::is_same<T1, BT<T>>::value ? BIT<T> - 5 : BIT<T> - 3;
        constexpr int N1 = std::is_same<T1, BT<T>>::value ? BIT<T> : BIT<T> - 2;
```
这两个变量的含义是是什么

**Comment by qwq2519** [comment]
const int r1 = v[0] ? 7 : 31,
                r2 = v[0] ? 10 : 34,
                r3 = v[0] ? 64 : (MAX<T> + 1);还有这三个常量

**Comment by yokeman-young** [comment]
阈值是64，最长的编码长度大于/小于阈值时，写入压缩文件中关于Huffman的信息是不同的。这些变量是针对不同情况下的一些量，一个是关于如何写入Huffman树，一方面是如何构建Huffman树。

**Comment by yokeman-young** [comment]
>   const int r1 = v[0] ? 7 : 31,
> 
>                 r2 = v[0] ? 10 : 34,
> 
>                 r3 = v[0] ? 64 : (MAX<T> + 1);还有这三个常量

我写这个程序的时候已经时隔三年，这些“魔法”变量具体细节已经不是很了解了，大概看了一下，N1，N2是关于如何写入压缩文件关于Huffman树的信息，r1,r2,r3是关于根据压缩文件中的Huffman树信息构建Huffman树。推荐Debug获取实现细节。

**Comment by qwq2519** [comment]
OK，谢谢
